codecov:
  require_ci_to_pass: false
  branch: main

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    patch:
      default:
        informational: true
    project:
      default:
        target: 80%
        threshold: 1%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  
ignore:
  - "*.ignore.*"
