version: "3.4"

services:
  doctors-portal-api:
    build:
      context: ./doctors-portal/src/API
    image: dmf-doctors-portal-api:dev
    ports:
      - 3020:8080
    env_file:
      - .env

  doctors-portal-ui:
    build:
      context: ./doctors-portal/src/UI
    image: dmf-doctors-portal-ui:dev
    ports:
      - 3200:2015
    environment:
      - "API_URL=doctors-portal-api:3020"
    depends_on:
      - doctors-portal-api

  landing-page:
    build:
      context: ./landing-page/src
    image: dmf-landing-page:dev
    ports:
      - 2200:2015

  cms-adapter:
    build:
      context: ./cms-adapter/src
    image: dmf-cms-adapter:dev
    ports:
      - 4020:8080
    environment:
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/ssl/aspnetapp.pfx"
    volumes:
      - ~/.aspnet/https:/ssl/:ro
    env_file:
      - .env

  phsa-adapter:
    build:
      context: ./phsa-adapter/src
    image: dmf-phsa-adapter:dev
    ports:
      - 5000:8080
    env_file:
      - .env

  oauth-server:
    build:
      context: ./oauth-server/src
    image: dmf-oauth-server:dev
    ports:
      - 5020:8080
    env_file:
      - .env
