kind: Template
apiVersion: v1
metadata:
  name: phsa-adapter-template

parameters:
  - description: openshift namespace prefix
    name: NAMESPACE_PREFIX
    required: true
  - description: openshift namespace env name
    name: ENV
    required: true
  - description: app name
    name: APP_NAME
    required: true
  - description: image tag for deployments
    name: TAG
    required: true
  - description: Hostname
    name: HOST
    required: true
  - description: ASPNET runtime environment (Development/Staging/Production)
    name: RUNTIME_ENVIRONMENT
    value: Staging
  - description: Password used for authentication
    from: "[A-Z0-9]{8}"
    generate: expression
    name: PASSWORD
  - description: oauth server url
    name: OAUTH_SERVER_URL
    required: true
  - description: oauth server client id
    name: OAUTH_CLIENTID
    required: true
  - description: oauth server client secret
    name: OAUTH_CLIENTSECRET
    required: true
  - description: OIDC_CLIENTID
    name: OIDC_CLIENTID
    required: true
  - description: INTROSPECTION_CLIENTSECRET
    name: INTROSPECTION_CLIENTSECRET
    required: true
  - description: INTROSPECTION_AUTHORITY
    name: INTROSPECTION_AUTHORITY
    required: true
  - description: TOKEN_AUTHORITY
    name: TOKEN_AUTHORITY 
    required: true
  - description: OIDC_SCOPE
    name: OIDC_SCOPE
    required: true
  - description: INTROSPECTION_CLIENTID
    name: INTROSPECTION_CLIENTID
    required: true
  - description: OIDC_ISSUER
    name: OIDC_ISSUER
    required: true 
  - description: FHIR_OAUTH_CLIENT_ID
    name: FHIR_OAUTH_CLIENT_ID
    required: true 
  - description: FHIR_OAUTH_CLIENT_SECRET
    name: FHIR_OAUTH_CLIENT_SECRET
    required: true
  - description: FHIR_AUTHORIZATION_ENDPOINT
    name: FHIR_AUTHORIZATION_ENDPOINT
    required: true
  - description: FHIR_TOKEN_ENDPOINT
    name: FHIR_TOKEN_ENDPOINT
    required: true
    - description: FHIR_INTROSPECTION_ENDPOINT
    name: FHIR_INTROSPECTION_ENDPOINT
    required: true
  - description: FHIR_SERVER_URL
    name: FHIR_SERVER_URL
    required: true
  - description: TEST_PHN
    name: TEST_PHN
    required: true
  - description: TEST_PHN_SYSTEM
    name: TEST_PHN_SYSTEM
    required: true
  - description: TEST_DL
    name: TEST_DL
    required: true
  - description: ICBC_ADAPTER_BASE_URI
    name: ICBC_ADAPTER_BASE_URI
    required: true
  - description: CORS_ORIGINS
    name: CORS_ORIGINS
    required: true
  - description: DOCUMENT_STORAGE_ADAPTER_URI
    name: DOCUMENT_STORAGE_ADAPTER_URI
    required: true
  - description: DOCUMENT_STORAGE_ADAPTER_JWT_SECRET
    name: DOCUMENT_STORAGE_ADAPTER_JWT_SECRET
    required: true
  - description: DOCUMENT_TRIAGE_SERVICE_URI
    name: DOCUMENT_TRIAGE_SERVICE_URI
    required: true
  - description: DOCUMENT_TRIAGE_SERVICE_JWT_SECRET
    name: DOCUMENT_TRIAGE_SERVICE_JWT_SECRET
    required: true
  - description: SPLUNK_COLLECTOR_URL
    name: SPLUNK_COLLECTOR_URL
    required: true
  - description: SPLUNK_TOKEN
    name: SPLUNK_TOKEN
    required: true

objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-config
      namespace: ${NAMESPACE_PREFIX}-${ENV}
      labels:
        app: ${APP_NAME}
        app.kubernetes.io/part-of: ${APP_NAME}
    data:
      ASPNETCORE_ENVIRONMENT: ${RUNTIME_ENVIRONMENT}
      KEY_RING_PATH: "/dpkeys"
      FHIR_OAUTH_CLIENT_ID: ${FHIR_OAUTH_CLIENT_ID}

  - kind: Secret
    apiVersion: v1
    type: Opaque
    metadata:
      name: ${APP_NAME}-secrets
      namespace: ${NAMESPACE_PREFIX}-${ENV}
      labels:
        app: ${APP_NAME}
        app.kubernetes.io/part-of: ${APP_NAME}
    stringData:
      USERNAME: "phsa"
      PASSWORD: "${PASSWORD}"
      AUTH__AUTHORITY: ${OAUTH_SERVER_URL}
      AUTH__CLIENTID: ${OAUTH_CLIENTID}
      AUTH__CLIENTSECRET: ${OAUTH_CLIENTSECRET}
      AUTH__OIDC__CLIENTID: ${OIDC_CLIENTID}
      AUTH__INTROSPECTION__CLIENTSECRET: ${INTROSPECTION_CLIENTSECRET}
      AUTH__INTROSPECTION__AUTHORITY: ${INTROSPECTION_AUTHORITY}
      AUTH__TOKEN__AUTHORITY: ${TOKEN_AUTHORITY}
      AUTH__OIDC__SCOPE: ${OIDC_SCOPE}
      AUTH__INTROSPECTION__CLIENTID: ${INTROSPECTION_CLIENTID}
      AUTH__OIDC__ISSUER: ${OIDC_ISSUER}
      FHIR_OAUTH_CLIENT_SECRET: ${FHIR_OAUTH_CLIENT_SECRET}
  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: ${APP_NAME}
        app.kubernetes.io/part-of: ${APP_NAME}
      name: ${APP_NAME}
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentconfig: ${APP_NAME}
      type: ClusterIP

  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      labels:
        app: ${APP_NAME}
        app.kubernetes.io/part-of: ${APP_NAME}
      name: ${APP_NAME}
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      host: ${HOST}
      port:
        targetPort: 8080-tcp
      # tls:
      #   insecureEdgeTerminationPolicy: Redirect
      #   termination: edge
      to:
        kind: Service
        name: ${APP_NAME}
        weight: 100
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Allow
      wildcardPolicy: None

  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: ${APP_NAME}
      labels:
        app: ${APP_NAME}
        app.kubernetes.io/part-of: ${APP_NAME}
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      podSelector:
        matchLabels:
          app: ${APP_NAME}
      ingress:
        - ports:
            - protocol: TCP
              port: 8080

  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      labels:
        app: ${APP_NAME}
        app.kubernetes.io/part-of: ${APP_NAME}
      name: ${APP_NAME}
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      replicas: 2
      selector:
        deploymentconfig: ${APP_NAME}
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: ${APP_NAME}
            app.kubernetes.io/part-of: ${APP_NAME}
            deploymentconfig: ${APP_NAME}
        spec:
          containers:
            - name: ${APP_NAME}
              envFrom:
                - configMapRef:
                    name: ${APP_NAME}-config
                - secretRef:
                    name: ${APP_NAME}-secrets
              image: docker-registry.default.svc:5000/${NAMESPACE_PREFIX}-tools/${APP_NAME}:${TAG}
              imagePullPolicy: Always
              volumeMounts:
                - mountPath: /dpkeys
                  name: dp-keys
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - name: dp-keys
              persistentVolumeClaim:
                claimName: ${APP_NAME}-key-ring
      test: false
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - phsa-adapter
            from:
              kind: ImageStreamTag
              name: ${APP_NAME}:${TAG}
              namespace: ${NAMESPACE_PREFIX}-tools

  - kind: "PersistentVolumeClaim"
    apiVersion: "v1"
    metadata:
      name: ${APP_NAME}-key-ring
      namespace: ${NAMESPACE_PREFIX}-${ENV}
      labels:
        app: ${APP_NAME}
        app.kubernetes.io/part-of: ${APP_NAME}
    spec:
      accessModes:
        - "ReadWriteMany"
      resources:
        requests:
          storage: "100Mi"
