kind: Template
apiVersion: v1
metadata:
  name: phsa-adapter-template

parameters:
  - description: openshift namespace prefix
    name: NAMESPACE_PREFIX
    required: true
  - description: openshift namespace env name
    name: ENV
    required: true
  - description: app name
    name: APP_NAME
    required: true
  - description: image tag for deployments
    name: TAG
    required: true
  - description: Reverse proxy known network
    name: KNOWN_NETWORKS
    value: ::ffff:10.97.0.0/16
  - description: ASPNET runtime environment (Development/Staging/Production)
    name: RUNTIME_ENVIRONMENT
    value: Staging

objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-phsa-adapter-config
      namespace: ${NAMESPACE_PREFIX}-${ENV}
      labels:
        app: ${APP_NAME}-phsa-adapter
        app.kubernetes.io/part-of: ${APP_NAME}
    data:
      ASPNETCORE_ENVIRONMENT: ${RUNTIME_ENVIRONMENT}
      KEY_RING_PATH: "/dpkeys"

  - kind: Secret
    apiVersion: v1
    type: Opaque
    metadata:
      name: ${APP_NAME}-phsa-adapter-secrets
      namespace: ${NAMESPACE_PREFIX}-${ENV}
      labels:
        app: ${APP_NAME}-phsa-adapter
        app.kubernetes.io/part-of: ${APP_NAME}
    stringData:

  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: ${APP_NAME}-phsa-adapter
        app.kubernetes.io/part-of: ${APP_NAME}
      name: ${APP_NAME}-phsa-adapter-api
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentconfig: ${APP_NAME}-phsa-adapter-api
      type: ClusterIP

  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      labels:
        app: ${APP_NAME}-phsa-adapter
        app.kubernetes.io/part-of: ${APP_NAME}
      name: ${APP_NAME}-phsa-adapter-api
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      host: -${ENV}.silver.devops.bcgov
      port:
        targetPort: 8080-tcp
      # tls:
      #   insecureEdgeTerminationPolicy: Redirect
      #   termination: edge
      to:
        kind: Service
        name: ${APP_NAME}-phsa-adapter-api
        weight: 100
      wildcardPolicy: None

  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: ${APP_NAME}-phsa-adapter
      labels:
        app: ${APP_NAME}-phsa-adapter
        app.kubernetes.io/part-of: ${APP_NAME}
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      podSelector:
        matchLabels:
          app: ${APP_NAME}-phsa-adapter
      ingress:
        - ports:
            - protocol: TCP
              port: 8080

  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      labels:
        app: ${APP_NAME}-phsa-adapter
        app.kubernetes.io/part-of: ${APP_NAME}
      name: ${APP_NAME}-phsa-adapter-api
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      replicas: 2
      selector:
        deploymentconfig: ${APP_NAME}-phsa-adapter-api
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: ${APP_NAME}-phsa-adapter
            app.kubernetes.io/part-of: ${APP_NAME}
            deploymentconfig: ${APP_NAME}-phsa-adapter-api
        spec:
          containers:
            - name: phsa-adapter-api
              envFrom:
                - configMapRef:
                    name: ${APP_NAME}-phsa-adapter-config
                - secretRef:
                    name: ${APP_NAME}-phsa-adapter-secrets
              image: docker-registry.default.svc:5000/${NAMESPACE_PREFIX}-tools/phsa-adapter-api:${TAG}
              imagePullPolicy: Always
              volumeMounts:
                - mountPath: /dpkeys
                  name: dp-keys
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - name: dp-keys
              persistentVolumeClaim:
                claimName: ${APP_NAME}-doctors-key-ring
      test: false
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - phsa-adapter-api
            from:
              kind: ImageStreamTag
              name: phsa-adapter-api:${TAG}
              namespace: ${NAMESPACE_PREFIX}-tools


  - kind: "PersistentVolumeClaim"
    apiVersion: "v1"
    metadata:
      name: ${APP_NAME}-phsa-adapter-key-ring
      namespace: ${NAMESPACE_PREFIX}-${ENV}
      labels:
        app: ${APP_NAME}-phsa-adapter
        app.kubernetes.io/part-of: ${APP_NAME}
    spec:
      accessModes:
        - "ReadWriteMany"
      resources:
        requests:
          storage: "100Mi"
