kind: Template
apiVersion: v1
metadata:
  name: doctors-portal-template

parameters:
  - description: openshift namespace prefix
    name: NAMESPACE_PREFIX
    required: true
  - description: openshift namespace env name
    name: ENV
    required: true
  - description: app name
    name: APP_NAME
    required: true
  - description: image tag for deployments
    name: TAG
    required: true
  - description: Reverse proxy known network
    name: KNOWN_NETWORKS
    value: ::ffff:10.97.0.0/16
  - description: ASPNET runtime environment (Development/Staging/Production)
    name: RUNTIME_ENVIRONMENT
    value: Staging

objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-doctors-api-config
      namespace: ${NAMESPACE_PREFIX}-${ENV}
      labels:
        app: ${APP_NAME}-doctors-portal
        app.kubernetes.io/part-of: ${APP_NAME}
    data:
      ASPNETCORE_ENVIRONMENT: ${RUNTIME_ENVIRONMENT}
      KEY_RING_PATH: "/dpkeys"

  - kind: Secret
    apiVersion: v1
    type: Opaque
    metadata:
      name: ${APP_NAME}-doctors-api-secrets
      namespace: ${NAMESPACE_PREFIX}-${ENV}
      labels:
        app: ${APP_NAME}-doctors-portal
        app.kubernetes.io/part-of: ${APP_NAME}
    stringData:

  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: ${APP_NAME}-doctors-portal
        app.kubernetes.io/part-of: ${APP_NAME}
      name: ${APP_NAME}-doctors-portal-api
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentconfig: ${APP_NAME}-doctors-portal-api
      type: ClusterIP

  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: ${APP_NAME}-doctors-portal
        app.kubernetes.io/part-of: ${APP_NAME}
      name: ${APP_NAME}-doctors-portal-ui
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      ports:
        - name: 2015-tcp
          port: 2015
          protocol: TCP
          targetPort: 2015
      selector:
        deploymentconfig: ${APP_NAME}-doctors-portal-ui
      type: ClusterIP

  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      labels:
        app: ${APP_NAME}-doctors-portal
        app.kubernetes.io/part-of: ${APP_NAME}
      name: ${APP_NAME}-doctors-portal-api
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      host: ${APP_NAME}-dft-doctors.bcgov
      path: /api
      port:
        targetPort: 8080-tcp
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${APP_NAME}-doctors-portal-api
        weight: 100
      wildcardPolicy: None

  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      labels:
        app: ${APP_NAME}-doctors-portal
        app.kubernetes.io/part-of: ${APP_NAME}
      name: ${APP_NAME}-doctors-portal-ui
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      host: ${APP_NAME}-dft-doctors.bcgov
      path: /
      port:
        targetPort: 2015-tcp
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${APP_NAME}-doctors-portal-ui
        weight: 100

  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: ${APP_NAME}-doctors-portal
      labels:
        app: ${APP_NAME}-doctors-portal
        app.kubernetes.io/part-of: ${APP_NAME}
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      podSelector:
        matchLabels:
          app: ${APP_NAME}-doctors-portal
      ingress:
        - ports:
            - protocol: TCP
              port: 2015
            - protocol: TCP
              port: 8080

  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      labels:
        app: ${APP_NAME}-doctors-portal
        app.kubernetes.io/part-of: ${APP_NAME}
      name: ${APP_NAME}-doctors-portal-api
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      replicas: 2
      selector:
        deploymentconfig: ${APP_NAME}-doctors-portal-api
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: ${APP_NAME}-doctors-portal
            app.kubernetes.io/part-of: ${APP_NAME}
            deploymentconfig: ${APP_NAME}-doctors-portal-api
        spec:
          containers:
            - name: doctors-portal-api
              env:
                - name: "ASPNETCORE_Kestrel__Certificates__Default__Path"
                  value: "/ssl/tls.crt"
              envFrom:
                - configMapRef:
                    name: ${APP_NAME}-doctors-api-config
                - secretRef:
                    name: ${APP_NAME}-doctors-api-secrets
              image: docker-registry.default.svc:5000/${NAMESPACE_PREFIX}-tools/doctors-portal-api:${TAG}
              imagePullPolicy: Always
              volumeMounts:
                - mountPath: /dpkeys
                  name: dp-keys
                - mountPath: /ssl
                  name: ssl
                  readonly: true
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - name: dp-keys
              persistentVolumeClaim:
                claimName: ${APP_NAME}-doctors-key-ring
            - name: ssl
              secret:
                secretName: ${APP_NAME}-ess-backend-ssl
      test: false
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - doctors-portal-api
            from:
              kind: ImageStreamTag
              name: doctors-portal-api:${TAG}
              namespace: ${NAMESPACE_PREFIX}-tools

  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      labels:
        app: ${APP_NAME}-doctors-portal
        app.kubernetes.io/part-of: ${APP_NAME}
      name: ${APP_NAME}-doctors-portal-ui
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      replicas: 2
      selector:
        deploymentconfig: ${APP_NAME}-doctors-portal-ui
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: ${APP_NAME}-doctors-portal
            app.kubernetes.io/part-of: ${APP_NAME}
            deploymentconfig: ${APP_NAME}-doctors-portal-ui
        spec:
          containers:
            - name: doctors-portal-ui
              image: docker-registry.default.svc:5000/${NAMESPACE_PREFIX}-tools/doctors-portal-ui:${TAG}
              imagePullPolicy: Always
              ports:
                - containerPort: 2015
                  protocol: TCP
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - doctors-portal-ui
            from:
              kind: ImageStreamTag
              name: doctors-portal-ui:${TAG}
              namespace: ${NAMESPACE_PREFIX}-tools

  - kind: "PersistentVolumeClaim"
    apiVersion: "v1"
    metadata:
      name: ${APP_NAME}-doctors-key-ring
      namespace: ${NAMESPACE_PREFIX}-${ENV}
      labels:
        app: ${APP_NAME}-doctors-portal
        app.kubernetes.io/part-of: ${APP_NAME}
    spec:
      accessModes:
        - "ReadWriteMany"
      resources:
        requests:
          storage: "100Mi"
