kind: Template
apiVersion: v1
metadata:
  name: doctors-portal-template

parameters:
  - description: openshift namespace prefix
    name: NAMESPACE_PREFIX
    required: true
  - description: openshift namespace env name
    name: ENV
    required: true
  - description: app name
    name: APP_NAME
    required: true
  - description: image tag for deployments
    name: TAG
    required: true
  - description: Reverse proxy known network
    name: KNOWN_NETWORKS
    value: ::ffff:10.97.0.0/16

objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-landing-page
      namespace: ${NAMESPACE_PREFIX}-${ENV}
      labels:
        app: ${APP_NAME}-landing-page
        app.kubernetes.io/part-of: ${APP_NAME}
    data:

  - kind: Secret
    apiVersion: v1
    type: Opaque
    metadata:
      name: ${APP_NAME}-landing-page
      namespace: ${NAMESPACE_PREFIX}-${ENV}
      labels:
        app: ${APP_NAME}-landing-page
        app.kubernetes.io/part-of: ${APP_NAME}
    stringData:

  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: ${APP_NAME}-landing-page
        app.kubernetes.io/part-of: ${APP_NAME}
      name: ${APP_NAME}-landing-page
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      ports:
        - name: 2015-tcp
          port: 2015
          protocol: TCP
          targetPort: 2015
      selector:
        deploymentconfig: ${APP_NAME}-landing-page
      type: ClusterIP

  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      labels:
        app: ${APP_NAME}-landing-page
        app.kubernetes.io/part-of: ${APP_NAME}
      name: ${APP_NAME}-landing-page
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      host: rsbc-dfp-landing-page-${APP_NAME}.silver.devops.bcgov
      path: /
      port:
        targetPort: 2015-tcp
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${APP_NAME}-landing-page
        weight: 100

  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: ${APP_NAME}-landing-page
      labels:
        app: ${APP_NAME}-landing-page
        app.kubernetes.io/part-of: ${APP_NAME}
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      podSelector:
        matchLabels:
          app: ${APP_NAME}-landing-page
      ingress:
        - ports:
            - protocol: TCP
              port: 2015

  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      labels:
        app: ${APP_NAME}-landing-page
        app.kubernetes.io/part-of: ${APP_NAME}
      name: ${APP_NAME}-landing-page
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      replicas: 2
      selector:
        deploymentconfig: ${APP_NAME}-landing-page
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: ${APP_NAME}-landing-page
            app.kubernetes.io/part-of: ${APP_NAME}
            deploymentconfig: ${APP_NAME}-landing-page
        spec:
          containers:
            - name: landing-page
              image: docker-registry.default.svc:5000/${NAMESPACE_PREFIX}-tools/landing-page:${TAG}
              imagePullPolicy: Always
              ports:
                - containerPort: 2015
                  protocol: TCP
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - landing-page
            from:
              kind: ImageStreamTag
              name: landing-page:${TAG}
              namespace: ${NAMESPACE_PREFIX}-tools
