name: ci-doctors-portal-api

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - "doctors-portal/src/API/**"
      - ".github/workflows/ci-doctors-portal-api.yml"

env:
  IMAGE_NAME: doctors-portal-api
  BUILD_ID: ${{ github.server_url }};${{ github.repository }};${{ github.ref }};${{ github.sha }};${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          echo BUILD_ID=$BUILD_ID
          docker build --build-arg BUILD_ID="6$BUILD_ID" . --file ./doctors-portal/src/API/Dockerfile --tag $IMAGE_NAME
