name: ci-doctors-portal-api

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - "doctors-portal/src/API/**"
      - ".github/workflows/ci-doctors-portal-api.yml"

env:
  IMAGE_NAME: doctors-portal-api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build --build-arg build_id="$GITHUB_SERVER_URL;$GITHUB_REPOSITORY;$GITHUB_REF_NAME;$GITHUB_SHA;$GITHUB_RUN_NUMBER" . --file ./doctors-portal/src/API/Dockerfile --tag $IMAGE_NAME
