name: ci-document-storage-adapter

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - 'document-storage-adapter/src/**'
      - '.github/workflows/ci-document-storage-adapter.yml'

env:
  IMAGE_NAME: document-storage-adapter
  RUN_NUMBER: ${{ github.run_number }}
  BUILD_PREFIX: ${{ vars.versionprefix }}
  BUILD_ID: ${{ github.server_url }}!${{ github.repository }}!${{ github.ref_name }}!${{ github.sha }}!${{ vars.versionprefix }}!${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'bcgov'
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build . --file ./document-storage-adapter/src/Dockerfile --build-arg BUILD_ID --build-arg BUILD_VERSION="$BUILD_PREFIX`expr $RUN_NUMBER % 256`" --tag $IMAGE_NAME
