name: ci-icbc-adapter

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - "icbc-adapter/src/**"
      - ".github/workflows/ci-icbc-adapter.yml"

env:
  IMAGE_NAME: icbc-adapter
  solution-folder: icbc-adapter/src/ 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: rlespinasse/git-commit-data-action@v1.x
      - name: Extract Branch Name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Setup .NET 
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
      - name: Install dependencies
        run: dotnet restore
        working-directory: ${{env.working-directory}}${{env.solution-folder}}

      - name: Install coverlet for code coverage
        run: dotnet tool install -g coverlet.console --version 1.7.2
        working-directory: ${{env.working-directory}}${{env.solution-folder}}

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ${{env.working-directory}}${{env.solution-folder}}

      - name: Test
        run: |          
          dotnet test -c Release --no-restore --verbosity normal           
        working-directory: ${{env.working-directory}}${{env.solution-folder}}
      - name: Build image
        run: docker build . --file ./icbc-adapter/src/Dockerfile --tag $IMAGE_NAME
