name: ci-migration-metrics-ui

on:
  push:
     branches: [main] #codecov uses default branch for dashboard stat. recommended change the default branch from main to dev
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - "migration-metrics/src/ClientApp/**"
      - ".github/workflows/ci-migration-metrics-ui.yml"

env:
  IMAGE_NAME: migration-metrics-ui
  working-directory: ./
  solution-folder: migration-metrics/src/ClientApp/
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: rlespinasse/git-commit-data-action@v1.x
      - name: Extract Branch Name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: actions/setup-node@v4
        with:
          node-version: '20.10'
      - run: npm ci
        working-directory: ${{env.working-directory}}${{env.solution-folder}}

      - run: npm run lint
        working-directory: ${{env.working-directory}}${{env.solution-folder}}

      - run: npm run build --if-present
        working-directory: ${{env.working-directory}}${{env.solution-folder}}
      - name: Test
        run: |          
          npm install
          npm test --codeCoverage=true --watch=false
        working-directory: ${{env.working-directory}}${{env.solution-folder}}
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          name: DMFT
          token: ${{ secrets.CODECOV_TOKEN }}
          # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
          flags: unittests
          # Environment variables to tag the upload with (e.g. PYTHON | OS,PYTHON)
          env_vars: javascript
