name: ci-phsa-adapter

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - 'phsa-adapter/src/**'
      - 'interfaces/icbc-adapter/**'
      - '.github/workflows/ci-phsa-adapter.yml'

env:
  IMAGE_NAME: phsa-adapter

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'bcgov'
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build . --file ./phsa-adapter/src/Dockerfile --tag $IMAGE_NAME
