name: ci-scheduler-service

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - 'scheduler/src/**'
      - '.github/workflows/ci-scheduler-service.yml'

env:
  IMAGE_NAME: scheduler-service

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'bcgov'
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build . --file ./scheduler/src/Dockerfile --tag $IMAGE_NAME
